[project]
name = "governance-dao"
description = "A comprehensive DAO governance system on Stacks blockchain"
authors = ["Alif Suryadi alifsuryadi037@gmail.com"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.governance-token-v2]
path = "contracts/governance-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.dao-governance-v2]
path = "contracts/dao-governance.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2